test-pro: tabbing changes

diff --git a/python/test-pro b/python/test-pro
--- a/python/test-pro
+++ b/python/test-pro
@@ -29,11 +29,15 @@ function getListenPath {
 
 TM_CONTAINER=$(sbctl create -v $VERSION -t "$DESC" -n | awk '/Creating container/ {print $NF}')
 
+TMP_FILES=""
+
 # set a trap to delete the sandbox at exit
 function tidyup {
-	echo "[INFO]Deleting $(sbctl delete $TM_CONTAINER)"
+  echo "[INFO]Deleting $(sbctl delete $TM_CONTAINER)"
+  echo "[INFO]Tidying up $TMP_FILES"
+  rm -rf $TMP_FILES
 }
-trap tidyup 0 1 2 3 15
+#trap tidyup 0 1 2 3 15
 
 TM_ADMIN_SECRET=$(sbctl get $TM_CONTAINER admin_secret)
 TM_DASH_URL=$(sbctl get $TM_CONTAINER dashboard)
@@ -100,124 +104,124 @@ fi
 
 
 if true; then
-	# API tests
-	# Dashboard createAPI
-	echo "[INFO]API checks: "
-	echo -n "  [INFO]Create: "
-	resp=$(createAPI.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name httpbin)
-	if [[ $? -lt 1 ]]; then
-		APIID=$(echo $resp | jq -r .ID)
-		echo "SUCCESS ($APIID)"
-	else
-		echo FAIL
-		exit 1
-	fi
-	# Dashboard getAPI
-	echo -n "  [INFO]List API $APIID: "
-	resp=$(getAPI.py $URL_AND_CREDENTIAL --apiid $APIID)
-	APIID2=$(echo $resp | jq -r .api_definition.api_id)
-	if [[ $APIID = $APIID2 ]]; then
-		echo "SUCCESS ($APIID2)"
-	else
-		echo FAIL
-		exit 1
-	fi
-	# create a second API
-	echo -n "  [INFO]Create Second API: "
-	resp=$(createAPI.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name httpbin)
-	if [[ $? -lt 1 ]]; then
-		APIID2=$(echo $resp | jq -r .ID)
-		echo "SUCCESS: ($APIID)"
-	else
-		echo "FAILED to create second API"
-		exit 1
-	fi
-	echo -n "  [INFO]List both APIs: "
-	# Dashboard getAPIs
-	if getAPIs.py $URL_AND_CREDENTIAL | grep -qiw $APIID; then
-		if getAPIs.py $URL_AND_CREDENTIAL | grep -qiw $APIID2; then
-			echo "SUCCESS ($APIID, $APIID2)"
-		else
-			echo FAIL second API $APIID2 missing
-			exit 1
-		fi
-	else
-		echo FAIL first API $APIID missing
-		exit 1
-	fi
-	# Dashboard deleteAPI
-	# delete the apis to have an empty dashboard
-	for API in $APIID $APIID2; do
-		echo -n "  [INFO]Delete API $API: "
-		resp=$(deleteAPI.py $URL_AND_CREDENTIAL --apiid $API)
-		if getAPIs.py $URL_AND_CREDENTIAL | grep -qiw $API; then
-			echo FAIL $resp
-			exit 1
-		else
-			echo SUCCESS
-		fi
-	done
-	# Dashboard createAPIs
-	numberToCreate=10
-	echo -n "  [INFO]Create APIs: "
-	resp=$(createAPIs.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name test --number $numberToCreate)
-	numberCreated=$(getAPIs.py $URL_AND_CREDENTIAL | grep -v \# | wc -l)
-	if [[ $numberCreated -eq $numberToCreate ]]; then
-		echo SUCCESS $numberCreated created
-	else
-		echo FAIL $numberCreated of $numberToCreate created
-		exit 1
-	fi
-	# Dashboard updateAPI
-	# create an API.
-	echo "  [INFO]Update API: "
-	echo -n "    [INFO]Create API: "
-	resp=$(createAPI.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name httpbin)
-	if [[ $? -lt 1 ]]; then
-		APIID=$(echo $resp | jq -r .ID)
-		echo "SUCCESS ($APIID)"
-	else
-		echo FAIL
-		exit 1
-	fi
-	# retrieve the API, make a note of the listen path
-	echo -n "    [INFO]getAPI $APIID: "
-	APIJSON=$(getAPI.py $URL_AND_CREDENTIAL --apiid $APIID)
-	if [[ -n $APIJSON ]]; then
-		echo SUCCESS
-	else
-		echo FAIL
-		exit 1
-	fi
-	# change the listen path in the json
-	UPDATED_API_JSON=$(echo $APIJSON | jq '(.api_definition.proxy.listen_path="/fred/")')
-	# update the API
-	TMPFILE=$(mktemp /tmp/XXXX-test-dashboard.json)
-	echo $UPDATED_API_JSON > $TMPFILE
-	resp=$(updateAPI.py $URL_AND_CREDENTIAL --template $TMPFILE --apiid $APIID)
-	rm $TMPFILE
-	# Retrieve the API and check the listen path is changed.
-	# Reusing the variable UPDATED_API_JSON to contain the API definition retrieved from the dashboard
-	# after posting the change back. It should be very like what was posted
-	echo -n "    [INFO]updateAPI $APIID: "
-	UPDATED_API_JSON=$(getAPI.py $URL_AND_CREDENTIAL --apiid $APIID)
-	UPDATED_LP=$(getListenPath "$UPDATED_API_JSON")
-	if [[ $UPDATED_LP = '"/fred/"' ]]; then
-		echo SUCCESS
-	else
-		echo FAIL
-		exit 1
-	fi
-	# Dashboard deleteAllAPIs
-	echo -n "  [INFO]Delete all APIs: "
-	resp=$(deleteAllAPIs.py $URL_AND_CREDENTIAL)
-	numberRemaining=$(getAPIs.py $URL_AND_CREDENTIAL | grep -v \# | wc -l)
-	if [[ $numberRemaining -eq 0 ]]; then
-		echo SUCCESS no APIs left
-	else
-		echo FAIL $numberRemaining left
-		exit 1
-	fi
+  # API tests
+  # Dashboard createAPI
+  echo "[INFO]API checks: "
+  echo -n "  [INFO]Create: "
+  resp=$(createAPI.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name httpbin)
+  if [[ $? -lt 1 ]]; then
+    APIID=$(echo $resp | jq -r .ID)
+    echo "SUCCESS ($APIID)"
+  else
+    echo FAIL
+    exit 1
+  fi
+  # Dashboard getAPI
+  echo -n "  [INFO]List API $APIID: "
+  resp=$(getAPI.py $URL_AND_CREDENTIAL --apiid $APIID --verbose)
+  APIID2=$(echo $resp | jq -r .api_definition.api_id)
+  if [[ $APIID = $APIID2 ]]; then
+    echo "SUCCESS ($APIID2)"
+  else
+    echo FAIL
+    exit 1
+  fi
+  # create a second API
+  echo -n "  [INFO]Create Second API: "
+  resp=$(createAPI.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name httpbin)
+  if [[ $? -lt 1 ]]; then
+    APIID2=$(echo $resp | jq -r .ID)
+    echo "SUCCESS: ($APIID)"
+  else
+    echo "FAILED to create second API"
+    exit 1
+  fi
+  echo -n "  [INFO]List both APIs: "
+  # Dashboard getAPIs
+  if getAPIs.py $URL_AND_CREDENTIAL | grep -qiw $APIID; then
+    if getAPIs.py $URL_AND_CREDENTIAL | grep -qiw $APIID2; then
+      echo "SUCCESS ($APIID, $APIID2)"
+    else
+      echo FAIL second API $APIID2 missing
+      exit 1
+    fi
+  else
+    echo FAIL first API $APIID missing
+    exit 1
+  fi
+  # Dashboard deleteAPI
+  # delete the apis to have an empty dashboard
+  for API in $APIID $APIID2; do
+    echo -n "  [INFO]Delete API $API: "
+    resp=$(deleteAPI.py $URL_AND_CREDENTIAL --apiid $API)
+    if getAPIs.py $URL_AND_CREDENTIAL | grep -qiw $API; then
+      echo FAIL $resp
+      exit 1
+    else
+      echo SUCCESS
+    fi
+  done
+  # Dashboard createAPIs
+  numberToCreate=10
+  echo -n "  [INFO]Create APIs: "
+  resp=$(createAPIs.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name test --number $numberToCreate)
+  numberCreated=$(getAPIs.py $URL_AND_CREDENTIAL | grep -v \# | wc -l)
+    if [[ $numberCreated -eq $numberToCreate ]]; then
+      echo SUCCESS $numberCreated created
+    else
+      echo FAIL $numberCreated of $numberToCreate created
+      exit 1
+    fi
+    # Dashboard updateAPI
+    # create an API.
+    echo "  [INFO]Update API: "
+    echo -n "    [INFO]Create API: "
+    resp=$(createAPI.py $URL_AND_CREDENTIAL --template $SCRIPTDIR/API-template-auth.json --name httpbin)
+    if [[ $? -lt 1 ]]; then
+      APIID=$(echo $resp | jq -r .ID)
+      echo "SUCCESS ($APIID)"
+    else
+      echo FAIL
+      exit 1
+    fi
+    # retrieve the API, make a note of the listen path
+    echo -n "    [INFO]getAPI $APIID: "
+    APIJSON=$(getAPI.py $URL_AND_CREDENTIAL --apiid $APIID --verbose)
+    if [[ $(echo $APIJSON | jq -r .api_definition.api_id) == $APIID ]]; then
+      echo SUCCESS
+    else
+      echo FAIL
+      exit 1
+    fi
+    # change the listen path in the json
+    UPDATED_API_JSON=$(echo $APIJSON | jq '(.api_definition.proxy.listen_path="/fred/")')
+    # update the API
+    TMPFILE=$(mktemp /tmp/XXXX-test-dashboard.json)
+    echo $UPDATED_API_JSON > $TMPFILE
+    resp=$(updateAPI.py $URL_AND_CREDENTIAL --template $TMPFILE --apiid $APIID)
+    TMP_FILES="$TMP_FILES $TMPFILE"
+    # Retrieve the API and check the listen path is changed.
+    # Reusing the variable UPDATED_API_JSON to contain the API definition retrieved from the dashboard
+    # after posting the change back. It should be very like what was posted
+    echo -n "    [INFO]updateAPI $APIID: "
+    UPDATED_API_JSON=$(getAPI.py $URL_AND_CREDENTIAL --apiid $APIID)
+    UPDATED_LP=$(getListenPath "$UPDATED_API_JSON")
+    if [[ $UPDATED_LP = '"/fred/"' ]]; then
+      echo SUCCESS
+    else
+      echo FAIL
+      exit 1
+    fi
+    # Dashboard deleteAllAPIs
+    echo -n "  [INFO]Delete all APIs: "
+    resp=$(deleteAllAPIs.py $URL_AND_CREDENTIAL)
+    numberRemaining=$(getAPIs.py $URL_AND_CREDENTIAL | grep -v \# | wc -l)
+      if [[ $numberRemaining -eq 0 ]]; then
+        echo SUCCESS no APIs left
+      else
+        echo FAIL $numberRemaining left
+        exit 1
+      fi
 fi
 
 # Policy tests
@@ -309,15 +313,15 @@ if true; then
     exit 1
   fi
   # Dashboard deleteAllAPIs
-	echo -n "  [INFO]Delete all APIs: "
-	resp=$(deleteAllAPIs.py $URL_AND_CREDENTIAL)
-	numberRemaining=$(getAPIs.py $URL_AND_CREDENTIAL | grep -v \# | wc -l)
-	if [[ $numberRemaining -eq 0 ]]; then
-		echo SUCCESS no APIs left
-	else
-		echo FAIL $numberRemaining left
-		exit 1
-	fi
+  echo -n "  [INFO]Delete all APIs: "
+  resp=$(deleteAllAPIs.py $URL_AND_CREDENTIAL)
+  numberRemaining=$(getAPIs.py $URL_AND_CREDENTIAL | grep -v \# | wc -l)
+    if [[ $numberRemaining -eq 0 ]]; then
+      echo SUCCESS no APIs left
+    else
+      echo FAIL $numberRemaining left
+      exit 1
+    fi
 fi
 
 # Key tests
