test-dashboard: added policy tests

diff --git a/python/test-dashboard b/python/test-dashboard
--- a/python/test-dashboard
+++ b/python/test-dashboard
@@ -30,7 +30,11 @@ function getListenPath {
 TM_CONTAINER=$(sbctl create -v $VERSION -t "$DESC" -n | awk '/Creating container/ {print $NF}')
 
 # set a trap to delete the sandbox at exit
-trap 'echo "[INFO]Deleting $(sbctl delete $TM_CONTAINER)"' 0 1 2 3 15
+function tidyup {
+	echo "[INFO]Deleting $(sbctl delete $TM_CONTAINER)"
+}
+
+trap tidyup 0 1 2 3 15
 
 TM_ADMIN_SECRET=$(sbctl get $TM_CONTAINER admin_secret)
 TM_DASH_URL=$(sbctl get $TM_CONTAINER dashboard)
@@ -83,10 +87,131 @@ else
 fi
 echo
 
-# API tests
-# Dashboard createAPI
-echo "[INFO]API checks: "
-echo -n "  [INFO]Create: "
+if false; then
+	# API tests
+	# Dashboard createAPI
+	echo "[INFO]API checks: "
+	echo -n "  [INFO]Create: "
+	resp=$(createAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name httpbin)
+	if [[ $? -lt 1 ]]; then
+		APIID=$(echo $resp | jq -r .ID)
+		echo "SUCCESS ($APIID)"
+	else
+		echo FAIL
+		exit 1
+	fi
+	# Dashboard getAPI
+	echo -n "  [INFO]List API $APIID: "
+	resp=$(getAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
+	APIID2=$(echo $resp | jq -r .api_definition.api_id)
+	if [[ $APIID = $APIID2 ]]; then
+		echo "SUCCESS ($APIID2)"
+	else
+		echo FAIL
+		exit 1
+	fi
+	# create a second API
+	echo -n "  [INFO]Create Second API: "
+	resp=$(createAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name httpbin)
+	if [[ $? -lt 1 ]]; then
+		APIID2=$(echo $resp | jq -r .ID)
+		echo "SUCCESS: ($APIID)"
+	else
+		echo "FAILED to create second API"
+		exit 1
+	fi
+	echo -n "  [INFO]List both APIs: "
+	# Dashboard getAPIs
+	if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $APIID; then
+		if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $APIID2; then
+			echo "SUCCESS ($APIID, $APIID2)"
+		else
+			echo FAIL second API $APIID2 missing
+			exit 1
+		fi
+	else
+		echo FAIL first API $APIID missing
+		exit 1
+	fi
+	# Dashboard deleteAPI
+	# delete the apis to have an empty dashboard
+	for API in $APIID $APIID2; do
+		echo -n "  [INFO]Delete API $API: "
+		resp=$(deleteAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $API)
+		if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $API; then
+			echo FAIL $resp
+			exit 1
+		else
+			echo SUCCESS
+		fi
+	done
+	# Dashboard createAPIs
+	numberToCreate=10
+	echo -n "  [INFO]Create APIs: "
+	resp=$(createAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name test --number $numberToCreate)
+	numberCreated=$(getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -v \# | wc -l)
+	if [[ $numberCreated -eq $numberToCreate ]]; then
+		echo SUCCESS $numberCreated created
+	else
+		echo FAIL $numberCreated of $numberToCreate created
+		exit 1
+	fi
+	# Dashboard updateAPI
+	# create an API.
+	echo "  [INFO]Update API: "
+	echo -n "    [INFO]Create API: "
+	resp=$(createAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name httpbin)
+	if [[ $? -lt 1 ]]; then
+		APIID=$(echo $resp | jq -r .ID)
+		echo "SUCCESS ($APIID)"
+	else
+		echo FAIL
+		exit 1
+	fi
+	# retrieve the API, make a note of the listen path
+	echo -n "    [INFO]getAPI $APIID: "
+	APIJSON=$(getAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
+	if [[ -n $APIJSON ]]; then
+		echo SUCCESS
+	else
+		echo FAIL
+		exit 1
+	fi
+	# change the listen path in the json
+	UPDATED_API_JSON=$(echo $APIJSON | jq '(.api_definition.proxy.listen_path="/fred/")')
+	# update the API
+	TMPFILE=$(mktemp /tmp/XXXX-test-dashboard.json)
+	echo $UPDATED_API_JSON > $TMPFILE
+	resp=$(updateAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $TMPFILE --apiid $APIID)
+	rm $TMPFILE
+	# Retrieve the API and check the listen path is changed.
+	# Reusing the variable UPDATED_API_JSON to contain the API definition retrieved from the dashboard
+	# after posting the change back. It should be very like what was posted
+	echo -n "    [INFO]updateAPI $APIID: "
+	UPDATED_API_JSON=$(getAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
+	UPDATED_LP=$(getListenPath "$UPDATED_API_JSON")
+	if [[ $UPDATED_LP = '"/fred/"' ]]; then
+		echo SUCCESS
+	else
+		echo FAIL
+		exit 1
+	fi
+	# Dashboard deleteAllAPIs
+	echo -n "  [INFO]Delete all APIs: "
+	resp=$(deleteAllAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY)
+	numberRemaining=$(getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -v \# | wc -l)
+	if [[ $numberRemaining -eq 0 ]]; then
+		echo SUCCESS no APIs left
+	else
+		echo FAIL $numberRemaining left
+		exit 1
+	fi
+fi
+
+# Policy tests
+# Dashboard createPolicy
+echo "[INFO]Policy checks: "
+echo -n "  [INFO]Create an API: "
 resp=$(createAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name httpbin)
 if [[ $? -lt 1 ]]; then
   APIID=$(echo $resp | jq -r .ID)
@@ -95,117 +220,79 @@ else
   echo FAIL
   exit 1
 fi
-# Dashboard getAPI
-echo -n "  [INFO]List API $APIID: "
-resp=$(getAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
-APIID2=$(echo $resp | jq -r .api_definition.api_id)
-if [[ $APIID = $APIID2 ]]; then
-  echo "SUCCESS ($APIID2)"
+echo -n "  [INFO]Create a policy for $APIID: "
+resp=$(createPolicy.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/policy-template.json --apiid $APIID)
+if [[ $? -lt 1 ]]; then
+  POLID=$(echo $resp | jq -r .Message)
+  echo "SUCCESS ($POLID)"
 else
   echo FAIL
   exit 1
 fi
-
-# create a second API
-echo -n "  [INFO]Create Second API: "
-resp=$(createAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name httpbin)
-if [[ $? -lt 1 ]]; then
-  APIID2=$(echo $resp | jq -r .ID)
-  echo "SUCCESS: ($APIID)"
+# Dashboard getPolicy
+echo -n "  [INFO]List Policy $POLID: "
+resp=$(getPolicy.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --policy $POLID)
+POLID2=$(echo $resp | jq -r ._id)
+if [[ $POLID = $POLID2 ]]; then
+  echo "SUCCESS ($POLID2)"
 else
-  echo "FAILED to create second API"
+  echo FAIL
   exit 1
 fi
-echo -n "  [INFO]List both APIs: "
-# Dashboard getAPIs
-if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $APIID; then
-  if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $APIID2; then
-    echo "SUCCESS ($APIID, $APIID2)"
+# create a second Policy
+echo -n "  [INFO]Create Second Policy: "
+resp=$(createPolicy.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/policy-template.json --apiid $APIID)
+if [[ $? -lt 1 ]]; then
+  POLID2=$(echo $resp | jq -r .Message)
+  echo "SUCCESS ($POLID2)"
+else
+  echo "FAILED to create second policy"
+  exit 1
+fi
+echo -n "  [INFO]List both policies: "
+# Dashboard getPolicies
+if getPolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $POLID; then
+  if getPolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $POLID2; then
+    echo "SUCCESS ($POLID, $POLID2)"
   else
-    echo FAIL second API $APIID2 missing
+    echo FAIL second policy $POLID2 missing
     exit 1
   fi
 else
-  echo FAIL first API $APIID missing
+  echo FAIL first policy $POLID missing
   exit 1
 fi
-echo -n "  [INFO]Delete API $APIID2: "
-# Dashboard deleteAPI
-resp=$(deleteAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID2)
-if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $APIID2; then
-  echo FAIL $resp
-  exit 1
-else
-  echo SUCCESS
-fi
-echo -n "  [INFO]Delete API $APIID: "
-resp=$(deleteAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
-if getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $APIID; then
-  echo FAIL $resp
-  exit 1
-else
-  echo SUCCESS
-fi
-# delete the second api to have an empty dashboard
-# Dashboard createAPIs
+# Dashboard deletePolicy
+# delete both policies to have none
+for POL in $POLID $POLID2; do
+	echo -n "  [INFO]Delete Policy $POL: "
+	resp=$(deletePolicy.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --policy $POL)
+	if getPolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -qiw $POL; then
+		echo FAIL $resp
+		exit 1
+	else
+		echo SUCCESS
+	fi
+done
+# Dashboard createPolicies
 numberToCreate=10
-echo -n "  [INFO]Create APIs: "
-resp=$(createAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name test1 --number $numberToCreate)
-numberCreated=$(getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -v \# | wc -l)
+echo -n "  [INFO]Create Policies: "
+resp=$(createPolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/policy-template.json --number $numberToCreate --apiid $APIID)
+numberCreated=$(getPolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -v \# | wc -l)
 if [[ $numberCreated -eq $numberToCreate ]]; then
   echo SUCCESS $numberCreated created
 else
   echo FAIL $numberCreated of $numberToCreate created
   exit 1
 fi
+exit
 # Dashboard deleteAllAPIs
-echo -n "  [INFO]Delete all APIs: "
-resp=$(deleteAllAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY)
-numberRemaining=$(getAPIs.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -v \# | wc -l)
+echo -n "  [INFO]Delete all Policies: "
+resp=$(deletePolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY)
+numberCreated=$(getPolicies.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY | grep -v \# | wc -l)
 if [[ $numberRemaining -eq 0 ]]; then
-  echo SUCCESS no APIs left
+  echo SUCCESS no Policies left
 else
   echo FAIL $numberRemaining left
-  exit 1
-fi
-
-# Dashboard updateAPI
-# create an API.
-echo "  [INFO]Update API: "
-echo -n "    [INFO]Create API: "
-resp=$(createAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $SCRIPTDIR/API-template-auth.json --name httpbin)
-if [[ $? -lt 1 ]]; then
-  APIID=$(echo $resp | jq -r .ID)
-  echo "SUCCESS ($APIID)"
-else
-  echo FAIL
-  exit 1
-fi
-# retrieve the API, make a note of the listen path
-echo -n "    [INFO]getAPI $APIID: "
-APIJSON=$(getAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
-if [[ -n $APIJSON ]]; then
-  echo SUCCESS
-else
-  echo FAIL
-  exit 1
-fi
-# change the listen path in the json
-UPDATED_API_JSON=$(echo $APIJSON | jq '(.api_definition.proxy.listen_path="/fred/")')
-# update the API
-TMPFILE=$(mktemp /tmp/XXXX-test-dashboard.json)
-echo $UPDATED_API_JSON > $TMPFILE
-resp=$(updateAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --template $TMPFILE --apiid $APIID)
-rm $TMPFILE
-# Retrieve the API and check the listen path is changed.
-# Reusing the variable UPDATED_API_JSON to contain the API definition retrieved from the dashboard
-# after posting the change back. It should be very like what was posted
-echo -n "    [INFO]updateAPI $APIID: "
-UPDATED_API_JSON=$(getAPI.py --dashboard $TM_DASH_URL --cred $TM_ADMIN_KEY --apiid $APIID)
-UPDATED_LP=$(getListenPath "$UPDATED_API_JSON")
-if [[ $UPDATED_LP = '"/fred/"' ]]; then
-  echo SUCCESS
-else
-  echo FAIL
   exit 1
 fi
